# Generated by Django 4.0.1 on 2022-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=50)),
                ('User_namme', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(max_length=50)),
                ('Passwd', models.CharField(max_length=50)),
                ('C_passs', models.CharField(max_length=50)),
            ],
        ),
    ]
